In [ ]:
#importing required libraries
import pandas as pd
import numpy as np
import plotly.express as px

In [ ]:
data = pd.read_csv('PS_20174392719_1491204439457_log.csv')
data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [ ]:
#Cheking for Null values

data.isnull().sum()  #does not have any null values

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [ ]:
data.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,463644.000000,4.636440e+05,4.636440e+05,4.636440e+05,4.636440e+05,4.636430e+05,463643.000000,463643.0
mean,13.491133,1.688000e+05,8.992499e+05,9.190083e+05,9.828097e+05,1.167319e+06,0.000475,0.0
std,3.553987,2.765594e+05,2.950359e+06,2.987721e+06,2.338954e+06,2.518724e+06,0.021778,0.0
min,1.000000,1.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0
25%,11.000000,1.346674e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.0
50%,14.000000,8.191337e+04,1.854278e+04,0.000000e+00,1.148958e+05,2.207192e+05,0.000000,0.0
75%,16.000000,2.256487e+05,1.730303e+05,2.132758e+05,8.932662e+05,1.206548e+06,0.000000,0.0
max,19.000000,1.000000e+07,3.893942e+07,3.894623e+07,4.148270e+07,4.148270e+07,1.000000,0.0

In [ ]:
type_transaction = data["type"].value_counts()
transaction = type_transaction.index
quantity = type_transaction.values

# plotting pie chart
fig = px.pie(data,
            values = quantity,
            names = transaction,
            hole = 0.4,
            title = "Distribution of Transaction Type")
fig.show()

In [ ]:
corr = data.corr()
corr["isFraud"].sort_values(ascending=False)

isFraud           1.000000
amount            0.044937
oldbalanceOrg    -0.001252
newbalanceDest   -0.002148
oldbalanceDest   -0.005209
newbalanceOrig   -0.006580
step             -0.022267
isFlaggedFraud         NaN
Name: isFraud, dtype: float64

In [ ]:
data["type"] = data["type"].map({"CASH_OUT": 1,
                                 "PAYMENT": 2,
                                 "CASH_IN": 3,
                                 "TRANSFER": 4,
                                 "DEBIT": 5})
data["isFraud"] = data["isFraud"].map({0: "No Fraud", 1: "Fraud"})
data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,2,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,No Fraud,0.0
1,1,2,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,No Fraud,0.0
2,1,4,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,Fraud,0.0
3,1,1,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,Fraud,0.0
4,1,2,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,No Fraud,0.0

In [ ]:
# CLassification model
# Splitting the data

from sklearn.model_selection import train_test_split
x = np.array(data[["type","amount", "oldbalanceOrg", "newbalanceOrig"]])
y = np.array(data["isFraud"])
# Training the data

    # using Decision tree classifier
from sklearn.tree import DecisionTreeClassifier
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state = 42)

model = DecisionTreeClassifier()

In [ ]:
# fit the training data in model

model.fit(x_train, y_train)
print(model.score(x_train,y_train))

1.0

In [ ]:
# Classifying the transaction by feeding input

# Features = [type, amount, oldbalanceOrg, newbalanceOrig]
features = np.array([[1, 10000, 5000, 100]])
print(model.predict(features))

['No Fraud']